stages:
  - prepare
  - qa
  - build
  - docker
  - deploy

variables:
  MYSQL_ROOT_PASSWORD: "rootpassword"
  MYSQL_USER: ssorder
  MYSQL_PASSWORD: ssorderpassword
  MYSQL_DATABASE: ssorder

commit-message:
  stage: prepare
  image: morawskim/pipeline-scripts
  script:
    - /pipeline/scripts/check-commit-title.rb $CI_COMMIT_TITLE

branch-name:
  stage: prepare
  image: morawskim/pipeline-scripts
  script:
    - /pipeline/scripts/check-branch-name.rb $CI_COMMIT_REF_NAME
  only:
    - branches

version:
  stage: prepare
  image: morawskim/pipeline-scripts
  script:
    - |
      VERSION=$(/pipeline/scripts/get-version.rb $CI_PROJECT_DIR/.git $CI_COMMIT_REF_NAME $CI_MERGE_REQUEST_SOURCE_BRANCH_NAME)
      echo "VERSION=$VERSION" | tee VERSION
      echo "COMMIT=$CI_COMMIT_SHA" | tee -a VERSION
      echo "PIPELINE=$CI_PIPELINE_ID" | tee -a VERSION
  only:
    - branches
    - merge_requests
  artifacts:
    paths:
      - VERSION
    expire_in: 30 days

composer:
  stage: prepare
  image: edbizarro/gitlab-ci-pipeline-php:7.3
  script:
    - php -v
    - composer install --prefer-dist --no-ansi --no-interaction --no-progress --no-scripts
    - cd vendor && ln -s bower-asset/ bower
  artifacts:
    paths:
      - vendor/
    expire_in: 30 days
    when: on_success
  cache:
    key: "$CI_COMMIT_REF_SLUG"
    paths:
      - /home/php/.composer/cache

yarn:
  stage: prepare
  image: edbizarro/gitlab-ci-pipeline-php:7.3
  script:
    - yarn -v
    - cd frontend && yarn install --frozen-lock-file
  artifacts:
    paths:
      - frontend/node_modules/
    expire_in: 5 days
    when: on_success
  cache:
    key: "$CI_COMMIT_REF_SLUG"
    paths:
      - /home/php/.cache/yarn/v1

codestyle:
  stage: qa
  image: edbizarro/gitlab-ci-pipeline-php:7.3
  script:
    - composer run phpcs | tee phpcs-report.xml
  dependencies:
    - composer
  artifacts:
    when: on_failure
    reports:
      junit: phpcs-report.xml

phpmd:
  stage: qa
  image: edbizarro/gitlab-ci-pipeline-php:7.3
  script:
    - composer run phpmd
  dependencies:
    - composer

phploc:
  stage: qa
  image: edbizarro/gitlab-ci-pipeline-php:7.3
  script:
    - composer run phploc
  dependencies:
    - composer

phpcpd:
  stage: qa
  image: edbizarro/gitlab-ci-pipeline-php:7.3
  script:
    - composer run phpcpd
  dependencies:
    - composer

php-lint:
  stage: qa
  image: edbizarro/gitlab-ci-pipeline-php:7.3
  script:
    - composer run phplint
  dependencies:
    - composer

phpstan:
  stage: qa
  image: edbizarro/gitlab-ci-pipeline-php:7.3
  script:
    - composer run phpstan
  dependencies:
    - composer

phpcf:
  stage: qa
  image: edbizarro/gitlab-ci-pipeline-php:7.3
  script:
    - composer run phpcf
  dependencies:
    - composer

openapi:
  stage: qa
  image: edbizarro/gitlab-ci-pipeline-php:7.3
  script:
    - composer run openapi
  dependencies:
    - composer
  artifacts:
    paths:
      - docs/openapi.yml
    expire_in: 30 days
    when: on_success

assets:
  stage: build
  image: edbizarro/gitlab-ci-pipeline-php:7.3
  script:
    - cd frontend && yarn build
  dependencies:
    - yarn
  artifacts:
    paths:
      - frontend/web/assets/build
      - frontend/webpack/stats.json
    expire_in: 30 days
    when: on_success

redoc:
  stage: build
  image: edbizarro/gitlab-ci-pipeline-php:7.3
  script:
    - composer run redoc
  dependencies:
    - openapi
  artifacts:
    paths:
      - docs/redoc/
    expire_in: 30 days
    when: on_success

swagger:
  stage: build
  image: edbizarro/gitlab-ci-pipeline-php:7.3
  script:
    - cp -rv ./vendor/swagger-api/swagger-ui/dist ./docs/swagger
    - cp docs/openapi.yml ./docs/swagger
    - sed -i -e's#https://petstore.swagger.io/v2/swagger.json#openapi.yml#' docs/swagger/index.html
  dependencies:
    - composer
    - openapi
  artifacts:
    paths:
      - docs/swagger/
    expire_in: 30 days
    when: on_success

pretier:
  stage: qa
  image: edbizarro/gitlab-ci-pipeline-php:7.3
  script:
    - cd frontend && yarn run prettier
  dependencies:
    - yarn

stylelint:
  stage: qa
  image: edbizarro/gitlab-ci-pipeline-php:7.3
  script:
    - cd frontend && yarn run stylelint
  dependencies:
    - yarn

eslint:
  stage: qa
  image: edbizarro/gitlab-ci-pipeline-php:7.3
  script:
    - cd frontend && yarn run eslint
  dependencies:
    - yarn

hadolint:
  stage: qa
  image: hadolint/hadolint:v1.16.3-debian
  script:
    - find -iname 'Dockerfile*' | xargs --max-lines=1 hadolint
  dependencies: []
  only:
    changes:
      - frontend/Dockerfile
      - node-cron/Dockerfile
      - docs/Dockerfile

security-checker:
  stage: qa
  image: edbizarro/gitlab-ci-pipeline-php:7.3
  script:
    - composer run security-checker
  allow_failure: true
  dependencies:
    - composer

npm-audit:
  stage: qa
  image: node:8.9-alpine
  script:
    - npm install -g yarn
    - cd frontend && yarn run audit-ci
  allow_failure: true
  dependencies:
    - yarn

codeception:
  stage: qa
  image: edbizarro/gitlab-ci-pipeline-php:7.3
  services:
    - mysql:5.6
  script:
    - cp .env.ci .env
    - ./yii migrate/up --interactive 0
    - composer run codecept-common
    - composer run codecept-frontend
  dependencies:
    - composer

sitespeed:
  stage: qa
  variables:
    URL: https://ssorder.snlb.pl
    SITESPEED_VERSION: 11.9.3
  before_script:
    - TMPFILE=$(mktemp /tmp/sistespeed.XXXXXX)
    - CSRF=$(curl -s --cookie-jar $TMPFILE $URL/site/login | grep 'meta name="csrf-token"'| grep -E -o 'content="(.*?)"' | cut -c10- | rev | cut -c2- | rev)
    - curl -H X-CSRF-Token:${CSRF} --cookie-jar $TMPFILE --cookie $TMPFILE -X POST -d"LoginForm%5Busername%5D=sitespeed&LoginForm%5Bpassword%5D=${SISTESPEED_PASSWORD}&LoginForm%5BrememberMe%5D=0&LoginForm%5BrememberMe%5D=1&login-button="  $URL/site/login
    - SESSION=$(cat  $TMPFILE | grep advanced-frontend | awk '{print $7}')
    - SITESPEED_OPTIONS="--cookie advanced-frontend=${SESSION}"
    - rm $TMPFILE
  script:
    - echo Use sitespeed at version "$SITESPEED_VERSION" with options "$SITESPEED_OPTIONS" and check url "$URL"
    - mkdir gitlab-exporter
    - wget -O ./gitlab-exporter/index.js https://gitlab.com/gitlab-org/gl-performance/raw/master/index.js
    - mkdir sitespeed-results
    - docker run --shm-size=1g --rm -v "$(pwd)":/sitespeed.io sitespeedio/sitespeed.io:$SITESPEED_VERSION --plugins.add ./gitlab-exporter --outputFolder sitespeed-results $URL $SITESPEED_OPTIONS
    - mv sitespeed-results/data/performance.json performance.json
  artifacts:
    paths:
      - performance.json
      - sitespeed-results/
    reports:
      performance: performance.json
  only:
    - schedules
  tags:
    - packer

.e2e:
  stage: testing
  image: morawskim/node10-google-chrome:74.0.3729.131
  script:
    - cd frontend && npm run e2e

.docker:
  stage: docker
  image:
    name: gcr.io/kaniko-project/executor:debug
    entrypoint: [""]
  dependencies:
    - composer
    - assets
    - version
  before_script:
    - source $CI_PROJECT_DIR/VERSION
    - echo "{\"auths\":{\"$CI_REGISTRY\":{\"username\":\"$CI_REGISTRY_USER\",\"password\":\"$CI_REGISTRY_PASSWORD\"}}}" > /kaniko/.docker/config.json
    - echo "" > $CI_PROJECT_DIR/.env
  except:
    - tags
    - api
    - external
    - pipelines
    - schedules
    - triggers
    - web
    - merge_requests
    - chats

docker:node:
  extends: .docker
  script:
      - /kaniko/executor --context $CI_PROJECT_DIR --dockerfile $CI_PROJECT_DIR/node-cron/Dockerfile --destination ${CI_REGISTRY}/${CI_PROJECT_PATH}/scheduler:latest
  only:
    refs:
      - develop
#    //todo mmo: obraz wykorzystuje kod PHP, ktory moze sie zmienic
    changes:
      - "node-cron/*"

docker:docs:
  extends: .docker
  script:
    - /kaniko/executor --context $CI_PROJECT_DIR/docs --dockerfile $CI_PROJECT_DIR/docs/Dockerfile --destination ${CI_REGISTRY}/${CI_PROJECT_PATH}/docs:latest
  only:
    - develop
  dependencies:
    - swagger
    - openapi
    - redoc
    - version

docker:develop:
  extends: .docker
  script:
      - /kaniko/executor --context $CI_PROJECT_DIR --dockerfile $CI_PROJECT_DIR/frontend/Dockerfile.prod --destination $CI_REGISTRY_IMAGE:latest
  only:
    - develop

docker:master:
  extends: .docker
  script:
    - /kaniko/executor --context $CI_PROJECT_DIR --dockerfile $CI_PROJECT_DIR/frontend/Dockerfile.prod --destination $CI_REGISTRY_IMAGE:stable --destination $CI_REGISTRY_IMAGE:$VERSION
  only:
    - master

docker:rc:
  extends: .docker
  script:
    - /kaniko/executor --context $CI_PROJECT_DIR --dockerfile $CI_PROJECT_DIR/frontend/Dockerfile.prod --destination $CI_REGISTRY_IMAGE:$VERSION
  only:
    - /^release-/

.trivy:
  stage: qa
  allow_failure: true
  before_script:
    - trivy --version
    - trivy --clear-cache
  dependencies: []
  variables:
    TRIVY_AUTH_URL: $CI_REGISTRY
    TRIVY_USERNAME: $CI_REGISTRY_USER
    TRIVY_PASSWORD: $CI_REGISTRY_PASSWORD
  only:
    - schedules
  tags:
    - packer
  cache:
    paths:
      - $CI_PROJECT_DIR/.trivycache/

trivy:develop:
  extends: .trivy
  script:
    - trivy --exit-code 1 --cache-dir $CI_PROJECT_DIR/.trivycache/ --severity CRITICAL $CI_REGISTRY_IMAGE:latest

tag_release:
  stage: deploy
  image: edbizarro/gitlab-ci-pipeline-php:7.2
  only:
    - master
  except:
    - tags
    - api
    - external
    - pipelines
    - schedules
    - triggers
    - web
    - merge_requests
    - chats
  before_script:
    - 'which ssh-agent || ( apt-get update -y && apt-get install openssh-client -y )'
    - eval $(ssh-agent -s)
    - ssh-add <(echo "$SSH_PRIVATE_KEY_FOR_TAGGING")
    - mkdir -p ~/.ssh
    - '[[ -f /.dockerenv ]] && echo -e "Host *\n\tStrictHostKeyChecking no\n\n" > ~/.ssh/config'
  script:
    - source ./VERSION
    - echo "GITLAB_USER $GITLAB_USER_NAME GITLAB_EMAIL $GITLAB_USER_EMAIL VERSION $VERSION"
    - git --version
    - git config --add user.name "${GITLAB_USER_NAME}"
    - git config --add user.email "${GITLAB_USER_EMAIL}"
    - git remote set-url --push origin ssh://git@gitlab.sensilabs.pl:6222/${CI_PROJECT_PATH}.git
    - git remote -v
    - git tag -a $VERSION -m "Releasing version v${VERSION} (by gitlab-ci)"
    - git push -o ci.skip origin --tags
  dependencies:
    - version
  variables:
    GIT_STRATEGY: clone

deploy_production:
  stage: deploy
  image: edbizarro/gitlab-ci-pipeline-php:7.3
  environment:
    name: production
    url: https://ssorder.snlb.pl
#  only:
#    - master
  when: manual
  before_script:
    - 'which ssh-agent || ( apt-get update -y && apt-get install openssh-client -y )'
    - eval $(ssh-agent -s)
    - ssh-add <(echo "$SSH_PRIVATE_KEY")
    - mkdir -p ~/.ssh
    - '[[ -f /.dockerenv ]] && echo -e "Host *\n\tStrictHostKeyChecking no\n\n" > ~/.ssh/config'
  script:
    - echo $PROD_SSORDER_PATH
    - echo "$PROD_CONFIG" > .env
    - DOCKER_AUTH=$(echo -n $CI_DEPLOY_USER:$CI_DEPLOY_PASSWORD | base64)
    - ssh -p22 deployer@192.168.15.28 mkdir -p $PROD_SSORDER_PATH/.runtime/{mysql,minio,redis}
    - scp -P22 -r .env docker-swarm.yml deployer@192.168.15.28:${PROD_SSORDER_PATH}/
    - |
      ssh -p22 deployer@192.168.15.28 << EOF
        set -e
        echo "{\"auths\":{\"$CI_REGISTRY\":{\"auth\":\"$DOCKER_AUTH\"}}}" > $PROD_SSORDER_PATH/config.json
        env PROD_SSORDER_PATH=${PROD_SSORDER_PATH} docker --config $PROD_SSORDER_PATH stack deploy --compose-file $PROD_SSORDER_PATH/docker-swarm.yml --with-registry-auth ssorder-prod
      EOF
    - >
      curl -X POST -H 'Content-Type: application/json' --data '{"text":"Nowa wersja ssorder!"}' https://chat.sensilabs.pl/hooks/$PROD_ROCKET_CHAT_NOTIFY_TOKEN
