stages:
  - prepare
  - qa
  - build
  - docker
  - deploy

variables:
  MYSQL_ROOT_PASSWORD: "rootpassword"
  MYSQL_USER: ssorder
  MYSQL_PASSWORD: ssorderpassword
  MYSQL_DATABASE: ssorder

.commit-message:
  stage: prepare
  image: morawskim/pipeline-scripts
  script:
    - ruby -e "exit 1 unless \"$CI_COMMIT_TITLE\" =~ /^#\d+[ -]+[\p{L}]+/u"

branch-name:
  stage: prepare
  image: morawskim/pipeline-scripts
  script:
    - ruby -e "exit 1 unless '$CI_COMMIT_REF_NAME' =~ /^master|develop$/ || '$CI_COMMIT_REF_NAME' =~ /^hotfix-|release-\d+\.\d+\.\d+$/ || '$CI_COMMIT_REF_NAME' =~ /^feature-\d+$/"
  only:
    - branches

version:
  stage: prepare
  image: morawskim/pipeline-scripts
  script:
    - |
      VERSION=$(/pipeline/scripts/get-version.rb $CI_PROJECT_DIR/.git $CI_COMMIT_REF_NAME $CI_MERGE_REQUEST_SOURCE_BRANCH_NAME)
      echo "VERSION=$VERSION" | tee VERSION
      echo "COMMIT=$CI_COMMIT_SHA" | tee -a VERSION
      echo "PIPELINE=$CI_PIPELINE_ID" | tee -a VERSION
  only:
    - branches
    - merge_requests
  artifacts:
    paths:
      - VERSION
    expire_in: 30 days

composer:
  stage: prepare
  image: edbizarro/gitlab-ci-pipeline-php:5.6
  script:
    - php -v
    - composer install --prefer-dist --no-ansi --no-interaction --no-progress --no-scripts
    - cd vendor && ln -s bower-asset/ bower
  artifacts:
    paths:
      - vendor/
    expire_in: 30 days
    when: on_success
  cache:
    key: "$CI_COMMIT_REF_SLUG"
    paths:
      - /home/php/.composer/cache

yarn:
  stage: prepare
  image: edbizarro/gitlab-ci-pipeline-php:5.6
  script:
    - yarn -v
    - cd frontend && yarn install --frozen-lock-file
  artifacts:
    paths:
      - frontend/node_modules/
    expire_in: 5 days
    when: on_success
  cache:
    key: "$CI_COMMIT_REF_SLUG"
    paths:
      - /home/php/.cache/yarn/v1

codestyle:
  stage: qa
  image: edbizarro/gitlab-ci-pipeline-php:5.6
  script:
    - ./vendor/bin/phpcs --report=junit --extensions=php | tee phpcs-report.xml
  dependencies:
    - composer
  artifacts:
    when: on_failure
    reports:
      junit: phpcs-report.xml

phpmd:
  stage: qa
  image: edbizarro/gitlab-ci-pipeline-php:5.6
  script:
    - ./vendor/bin/phpmd --ignore-violations-on-exit ./frontend/,./common/,./console/ text ./phpmd-ruleset.xml
  dependencies:
    - composer

phploc:
  stage: qa
  image: edbizarro/gitlab-ci-pipeline-php:5.6
  script:
    - ./vendor/bin/phploc ./frontend/ ./common/ ./console/
  dependencies:
    - composer

phpcpd:
  stage: qa
  image: edbizarro/gitlab-ci-pipeline-php:5.6
  script:
    - ./vendor/bin/phpcpd --exclude=views/ --progress ./frontend/ ./common/ ./console/
  dependencies:
    - composer

php-lint:
  stage: qa
  image: edbizarro/gitlab-ci-pipeline-php:5.6
  script:
    - ./vendor/bin/parallel-lint --exclude vendor/ .
  dependencies:
    - composer

phpstan-deprecation-rules:
  stage: qa
  image: edbizarro/gitlab-ci-pipeline-php:7.1
  script:
    - composer global require  phpstan/phpstan-deprecation-rules
    - ~/.composer/vendor/bin/phpstan analyse --no-progress --no-interaction ./frontend ./common ./console
  dependencies:
    - composer

phpcf:
  stage: qa
  image: edbizarro/gitlab-ci-pipeline-php:5.6
  script:
    - ./vendor/bin/phpcf --target 7.2 ./frontend/ console/ ./common/
  dependencies:
    - composer

assets:
  stage: build
  image: edbizarro/gitlab-ci-pipeline-php:5.6
  script:
    - cd frontend && yarn build
  dependencies:
    - yarn
  artifacts:
    paths:
      - frontend/web/assets/build
    expire_in: 30 days
    when: on_success

pretier:
  stage: qa
  image: edbizarro/gitlab-ci-pipeline-php:5.6
  script:
    - cd frontend && ./node_modules/.bin/prettier --check './webpack/**'
  dependencies:
    - yarn

stylelint:
  stage: qa
  image: edbizarro/gitlab-ci-pipeline-php:5.6
  script:
    - cd frontend && ./node_modules/.bin/stylelint ./webpack
  dependencies:
    - yarn

eslint:
  stage: qa
  image: edbizarro/gitlab-ci-pipeline-php:5.6
  script:
    - cd frontend && ./node_modules/.bin/eslint ./webpack
  dependencies:
    - yarn

hadolint:
  stage: qa
  image: hadolint/hadolint:v1.16.3-debian
  script:
    - hadolint frontend/Dockerfile
    - find -iname 'Dockerfile*' | xargs --max-lines=1 hadolint
  dependencies: []
  only:
    changes:
      - frontend/Dockerfile

security-checker:
  stage: qa
  image: edbizarro/gitlab-ci-pipeline-php:5.6
  script:
    - ./vendor/bin/security-checker security:check ./composer.lock --format text
  allow_failure: true
  dependencies:
    - composer

npm-audit:
  stage: qa
  image: node:8.9-alpine
  script:
    - npm install -g yarn
    - cd frontend && npm run audit-ci -m
  allow_failure: true
  dependencies:
    - yarn

codeception:
  stage: qa
  image: edbizarro/gitlab-ci-pipeline-php:5.6
  services:
    - mysql:5.6
  script:
    - cp .env.ci .env
    - ./yii migrate/up --interactive 0
    - cd ./common && ../vendor/bin/codecept run unit
    - cd ..
    - cd ./frontend && ../vendor/bin/codecept run unit
  dependencies:
    - composer

.e2e:
  stage: testing
  image: morawskim/node10-google-chrome:74.0.3729.131
  script:
    - cd frontend && npm run e2e

.docker:
  stage: docker
  image:
    name: gcr.io/kaniko-project/executor:debug
    entrypoint: [""]
  dependencies:
    - composer
    - assets
    - version
  before_script:
    - source $CI_PROJECT_DIR/VERSION
    - echo "{\"auths\":{\"$CI_REGISTRY\":{\"username\":\"$CI_REGISTRY_USER\",\"password\":\"$CI_REGISTRY_PASSWORD\"}}}" > /kaniko/.docker/config.json
    - echo "" > $CI_PROJECT_DIR/.env

docker:develop:
  extends: .docker
  script:
      - /kaniko/executor --context $CI_PROJECT_DIR --dockerfile $CI_PROJECT_DIR/frontend/Dockerfile.prod --destination $CI_REGISTRY_IMAGE:latest
  only:
    - develop

docker:master:
  extends: .docker
  script:
    - /kaniko/executor --context $CI_PROJECT_DIR --dockerfile $CI_PROJECT_DIR/frontend/Dockerfile.prod --destination $CI_REGISTRY_IMAGE:stable --destination $CI_REGISTRY_IMAGE:$VERSION
  only:
    - master

docker:rc:
  extends: .docker
  script:
    - /kaniko/executor --context $CI_PROJECT_DIR --dockerfile $CI_PROJECT_DIR/frontend/Dockerfile.prod --destination $CI_REGISTRY_IMAGE:$VERSION
  only:
    - /^release-/

tag_release:
  stage: deploy
  image: edbizarro/gitlab-ci-pipeline-php:7.2
  only:
    - master
  except:
    - tags
  before_script:
    - 'which ssh-agent || ( apt-get update -y && apt-get install openssh-client -y )'
    - eval $(ssh-agent -s)
    - ssh-add <(echo "$SSH_PRIVATE_KEY_FOR_TAGGING")
    - mkdir -p ~/.ssh
    - '[[ -f /.dockerenv ]] && echo -e "Host *\n\tStrictHostKeyChecking no\n\n" > ~/.ssh/config'
  script:
    - source ./VERSION
    - echo "GITLAB_USER $GITLAB_USER_NAME GITLAB_EMAIL $GITLAB_USER_EMAIL VERSION $VERSION"
    - git --version
    - git config --add user.name "${GITLAB_USER_NAME}"
    - git config --add user.email "${GITLAB_USER_EMAIL}"
    - git remote set-url --push origin ssh://git@gitlab.sensilabs.pl:6222/${CI_PROJECT_PATH}.git
    - git remote -v
    - git tag -a $VERSION -m "Releasing version v${VERSION} (by gitlab-ci)"
    - git push -o ci.skip origin --tags
  dependencies:
    - version
  variables:
    GIT_STRATEGY: clone

deploy_production:
  stage: deploy
  image: edbizarro/gitlab-ci-pipeline-php:5.6
  environment:
    name: production
    url: https://ssorder.snlb.pl
#  only:
#    - master
  when: manual
  before_script:
    - 'which ssh-agent || ( apt-get update -y && apt-get install openssh-client -y )'
    - eval $(ssh-agent -s)
    - ssh-add <(echo "$SSH_PRIVATE_KEY")
    - mkdir -p ~/.ssh
    - '[[ -f /.dockerenv ]] && echo -e "Host *\n\tStrictHostKeyChecking no\n\n" > ~/.ssh/config'
  script:
    - echo $PROD_SSORDER_PATH
    - echo "$PROD_CONFIG" > .env
    - DOCKER_AUTH=$(echo -n $CI_DEPLOY_USER:$CI_DEPLOY_PASSWORD | base64)
    - ssh -p22 deployer@192.168.15.28 mkdir -p $PROD_SSORDER_PATH/.runtime/{mysql,minio}
    - scp -P22 -r .env docker-swarm.yml deployer@192.168.15.28:${PROD_SSORDER_PATH}/
    - |
      ssh -p22 deployer@192.168.15.28 << EOF
        set -e
        echo "{\"auths\":{\"$CI_REGISTRY\":{\"auth\":\"$DOCKER_AUTH\"}}}" > $PROD_SSORDER_PATH/config.json
        env PROD_SSORDER_PATH=${PROD_SSORDER_PATH} docker --config $PROD_SSORDER_PATH stack deploy --compose-file $PROD_SSORDER_PATH/docker-swarm.yml --with-registry-auth ssorder-prod
      EOF
    - >
      curl -X POST -H 'Content-Type: application/json' --data '{"text":"Nowa wersja ssorder!"}' https://chat.sensilabs.pl/hooks/$PROD_ROCKET_CHAT_NOTIFY_TOKEN
