version: '3.4'
services:
  docs:
    image: registry.sensilabs.pl/sensilabs/ssorder/docs
    networks:
      - default
      - traefik
    deploy:
      labels:
        traefik.port: 8080
        traefik.backend: "ssorder-developer"
        traefik.frontend.rule: "Host:developer.ssorder.snlb.pl"
networks:
  traefik:
    external: true
# vim: ft=docker-compose.yaml: